version: '3.9'

services:
  nextjs-app:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: carbon_db
      POSTGRES_USER: carbon_user
      POSTGRES_PASSWORD: carbon_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
